/**
 * Generates src/generated/tokens.ts from tokens.json.
 *
 * tokens.json (DTCG) is the single source of truth for the entire KitchenKin
 * design system. This script produces the portable TypeScript token object
 * consumed by kkds-web and (future) kkds-mobile.
 *
 * The web CSS theme is generated by kkds-web's build-tokens.mjs, which reads
 * from this same tokens.json.
 *
 * Output: src/generated/tokens.ts
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const tokensPath = join(root, "tokens.json");
const tsOutDir = join(root, "src", "generated");

/** Resolve a DTCG node's $value, following {alias} references. */
function resolveValue(node, tokens) {
  const raw = node?.$value;
  if (typeof raw === "string" && raw.startsWith("{") && raw.endsWith("}")) {
    const path = raw.slice(1, -1).split(".");
    let cur = tokens;
    for (const key of path) cur = cur?.[key];
    return resolveValue(cur, tokens);
  }
  return raw;
}

function toFontStack(value) {
  return Array.isArray(value) ? value.join(", ") : value;
}

function colorEntries(scope, tokens) {
  const out = {};
  for (const [name, node] of Object.entries(tokens.color[scope])) {
    if (name.startsWith("$")) continue;
    out[name] = resolveValue(node, tokens);
  }
  return out;
}

function motionEntries(group, tokens) {
  const out = {};
  for (const [name, node] of Object.entries(tokens.motion[group])) {
    if (name.startsWith("$")) continue;
    out[name] = resolveValue(node, tokens);
  }
  return out;
}

function buildTs(tokens) {
  const portable = {
    color: {
      light: colorEntries("light", tokens),
      dark: colorEntries("dark", tokens),
    },
    fontFamily: {
      sans: resolveValue(tokens.typography.fontFamily.sans, tokens),
      serif: resolveValue(tokens.typography.fontFamily.serif, tokens),
      mono: resolveValue(tokens.typography.fontFamily.mono, tokens),
    },
    radius: resolveValue(tokens.radius.base, tokens),
    spacing: resolveValue(tokens.spacing.base, tokens),
    motion: {
      duration: motionEntries("duration", tokens),
      easing: motionEntries("easing", tokens),
    },
  };
  return `/* GENERATED FROM tokens.json -- DO NOT EDIT. Run \`pnpm tokens\` in lib/kkds-common. */
// Portable design tokens (colors as hex, motion as CSS strings).
// Web consumes the color theme via kkds-web's src/index.css.
// All platforms import this object so the whole product shares one source of truth.
export const tokens = ${JSON.stringify(portable, null, 2)} as const;

export type Tokens = typeof tokens;
export default tokens;
`;
}

export function buildTokens() {
  const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));
  mkdirSync(tsOutDir, { recursive: true });
  writeFileSync(join(tsOutDir, "tokens.ts"), buildTs(tokens));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  buildTokens();
  process.stdout.write("Generated src/generated/tokens.ts\n");
}
